const fs = require('fs');

const file = 'src/data/translations.ts';
let content = fs.readFileSync(file, 'utf8');

const jobscoutTranslations = {
  en: `        jobscout: {
            title: "AI Job Discovery Agent",
            subtitle: "Automatically scans job portals, scores each listing by salary, tech stack & experience, and generates tailored resumes that pass ATS filters.",
            yourProfile: "Your Profile",
            あなたのプロフィールDesc: "Import your portfolio or paste your resume below",
            importFromPortfolio: "Import from Portfolio",
            searchPrefs: "Search Preferences",
            salaryRange: "Salary Range",
            location: "Location",
            workMode: "Work Mode",
            experienceLevel: "Experience Level",
            scoutJobs: "Scout Jobs For Me",
            scanning: "Scanning Job Portals",
            scanningDesc: "Searching LinkedIn, Naukri, Indeed, Glassdoor...",
            jobsFound: "Jobs Found",
            all: "All",
            worthApplying: "Worth Applying",
            rescan: "Rescan",
            generateResume: "Generate Resume",
            backToJobs: "Back to all jobs",
            topStrengths: "Top Strengths",
            criticalGaps: "Critical Gaps",
            successRate: "Estimated Success Rate",
            tailoredResume: "Tailored Resume",
            copy: "Copy",
            downloadPdf: "Download PDF",
            gapPlan: "Skill Gap Recovery Plan",
            appTips: "Application Tips"
        },
`,
  hi: `        jobscout: {
            title: "एआई जॉब डिस्कवरी एजेंट",
            subtitle: "स्वचालित रूप से जॉब पोर्टल स्कैन करता है, सैलरी, टेक स्टैक और अनुभव के आधार पर स्कोर करता है, और ATS-अनुकूल रिज्यूमे बनाता है।",
            yourProfile: "आपकी प्रोफाइल",
            yourProfileDesc: "अपना पोर्टफोलियो आयात करें या नीचे अपना रिज्यूमे पेस्ट करें",
            importFromPortfolio: "पोर्टफोलियो से आयात करें",
            searchPrefs: "खोज प्राथमिकताएँ",
            salaryRange: "वेतन सीमा",
            location: "स्थान",
            workMode: "कार्य मोड",
            experienceLevel: "अनुभव स्तर",
            scoutJobs: "मेरे लिए जॉब खोजें",
            scanning: "जॉब पोर्टल स्कैन कर रहा है",
            scanningDesc: "LinkedIn, Naukri, Indeed, Glassdoor पर खोज रहा है...",
            jobsFound: "नौकरियां मिलीं",
            all: "सभी",
            worthApplying: "आवेदन करने योग्य",
            rescan: "फिर से स्कैन करें",
            generateResume: "रिज्यूमे बनाएं",
            backToJobs: "सभी जॉब्स पर वापस लौटें",
            topStrengths: "शीर्ष ताकतें",
            criticalGaps: "गंभीर कमियां",
            successRate: "अनुमानित सफलता दर",
            tailoredResume: "अनुकूलित रिज्यूमे",
            copy: "कॉपी करें",
            downloadPdf: "पीडीएफ डाउनलोड करें",
            gapPlan: "कौशल अंतराल रिकवरी योजना",
            appTips: "आवेदन संबंधित टिप्स"
        },
`,
  te: `        jobscout: {
            title: "ఏఐ ఉద్యోగ అన్వేషణ ఏజెంట్",
            subtitle: "ఆటోమేటిక్ గా జాబ్ పోర్టల్స్ స్కాన్ చేస్తుంది, జీతం, టెక్ స్టాక్ & అనుభవం ఆధారంగా స్కోర్ చేసి, ఏటీఎస్ కి సరిపోయే రెజ్యూమెలను తయారు చేస్తుంది.",
            yourProfile: "మీ ప్రొఫైల్",
            yourProfileDesc: "మీ పోర్ట్‌ఫోలియోను ఇంపోర్ట్ చేయండి లేదా కింద మీ రెజ్యూమెను పేస్ట్ చేయండి",
            importFromPortfolio: "పోర్ట్‌ఫోలియో నుండి ఇంపోర్ట్ చేయండి",
            searchPrefs: "సెర్చ్ ప్రాధాన్యతలు",
            salaryRange: "జీతం పరిధి",
            location: "స్థానం",
            workMode: "పని విధానం",
            experienceLevel: "అనుభవ స్థాయి",
            scoutJobs: "నా కోసం ఉద్యోగాలు వెతకండి",
            scanning: "జాబ్ పోర్టల్స్ స్కాన్ చేస్తోంది",
            scanningDesc: "LinkedIn, Naukri, Indeed, Glassdoor లో వెతుకుతోంది...",
            jobsFound: "ఉద్యోగాలు దొరికాయి",
            all: "అన్నీ",
            worthApplying: "అప్లై చేయదగినవి",
            rescan: "మళ్ళీ స్కాన్ చేయండి",
            generateResume: "రెజ్యూమె తయారు చేయండి",
            backToJobs: "అన్ని ఉద్యోగాలకు తిరిగి వెళ్ళండి",
            topStrengths: "ప్రధాన బలాలు",
            criticalGaps: "ముఖ్యమైన లోపాలు",
            successRate: "అంచనా వేసిన సక్సెస్ రేటు",
            tailoredResume: "అనుకూల రెజ్యూమె",
            copy: "కాపీ చేయండి",
            downloadPdf: "పీడీఎఫ్ డౌన్‌లోడ్ చేయండి",
            gapPlan: "స్కిల్ గ్యాప్ రికవరీ ప్లాన్",
            appTips: "అప్లికేషన్ చిట్కాలు"
        },
`,
  ta: `        jobscout: {
            title: "செயற்கை நுண்ணறிவு வேலை தேடல் முகவர்",
            subtitle: "தானாக வேலை இணையதளங்களை ஸ்கேன் செய்கிறது, சம்பளம், டெக் ஸ்டாக் மற்றும் அனுபவத்தின் அடிப்படையில் மதிப்பெண் அளித்து, ஏடிஎஸ்-க்கு ஏற்ற ரெஸ்யூம்களை உருவாக்குகிறது.",
            yourProfile: "உங்கள் விவரக்குறிப்பு",
            yourProfileDesc: "உங்கள் போர்ட்ஃபோலியோவை இறக்குமதி செய்யுங்கள் அல்லது உங்கள் ரெஸ்யூமை கீழே ஒட்டவும்",
            importFromPortfolio: "போர்ட்ஃபோலியோவிலிருந்து இறக்குமதி செய்",
            searchPrefs: "தேடல் விருப்பங்கள்",
            salaryRange: "சம்பள வரம்பு",
            location: "இடம்",
            workMode: "பணி முறை",
            experienceLevel: "அனுபவ நிலை",
            scoutJobs: "எனக்காக வேலைகளைத் தேடுங்கள்",
            scanning: "வேலை இணையதளங்களை ஸ்கேன் செய்கிறது",
            scanningDesc: "LinkedIn, Naukri, Indeed, Glassdoor-ல் தேடப்படுகிறது...",
            jobsFound: "வேலைகள் கிடைத்துள்ளன",
            all: "அனைத்தும்",
            worthApplying: "விண்ணப்பிக்க தகுதியானவை",
            rescan: "மீண்டும் ஸ்கேன் செய்",
            generateResume: "ரெஸ்யூமை உருவாக்கு",
            backToJobs: "அனைத்து வேலைகளுக்கும் திரும்புக",
            topStrengths: "முக்கிய பலங்கள்",
            criticalGaps: "முக்கியமான குறைபாடுகள்",
            successRate: "மதிப்பிடப்பட்ட வெற்றி விகிதம்",
            tailoredResume: "தனிப்பயனாக்கப்பட்ட ரெஸ்யூம்",
            copy: "நகலெடு",
            downloadPdf: "பிடிஎஃப் பதிவிறக்கு",
            gapPlan: "திறன் குறைபாடு மீட்பு திட்டம்",
            appTips: "விண்ணப்ப குறிப்புகள்"
        },
`,
  kn: `        jobscout: {
            title: "ಎಐ ಉದ್ಯೋಗ ಶೋಧನೆ ಏಜೆಂಟ್",
            subtitle: "ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಉದ್ಯೋಗ ಪೋರ್ಟಲ್‌ಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತದೆ, ವೇತನ, ಟೆಕ್ ಸ್ಟ್ಯಾಕ್ ಮತ್ತು ಅನುಭವದ ಆಧಾರದ ಮೇಲೆ ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ, ಎಟಿಎಸ್-ಸ್ನೇಹಿ ರೆಸ್ಯೂಮ್‌ಗಳನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತದೆ.",
            yourProfile: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್",
            yourProfileDesc: "ನಿಮ್ಮ ಪೋರ್ಟ್‌ಫೋಲಿಯೊವನ್ನು ಆಮದು ಮಾಡಿ ಅಥವಾ ಕೆಳಗೆ ನಿಮ್ಮ ರೆಸ್ಯೂಮ್ ಅನ್ನು ಅಂಟಿಸಿ",
            importFromPortfolio: "ಪೋರ್ಟ್‌ಫೋಲಿಯೊದಿಂದ ಆಮದು ಮಾಡಿ",
            searchPrefs: "ಹುಡುಕಾಟ ಆದ್ಯತೆಗಳು",
            salaryRange: "ವೇತನ ಶ್ರೇಣಿ",
            location: "ಸ್ಥಳ",
            workMode: "ಕೆಲಸದ ವಿಧಾನ",
            experienceLevel: "ಅನುಭವದ ಮಟ್ಟ",
            scoutJobs: "ನನಗಾಗಿ ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ",
            scanning: "ಉದ್ಯೋಗ ಪೋರ್ಟಲ್‌ಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ",
            scanningDesc: "LinkedIn, Naukri, Indeed, Glassdoor ನಲ್ಲಿ ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
            jobsFound: "ಉದ್ಯೋಗಗಳು ದೊರೆತಿವೆ",
            all: "ಎಲ್ಲಾ",
            worthApplying: "ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಯೋಗ್ಯ",
            rescan: "ಮತ್ತೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
            generateResume: "ರೆಸ್ಯೂಮ್ ರಚಿಸಿ",
            backToJobs: "ಎಲ್ಲಾ ಉದ್ಯೋಗಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
            topStrengths: "ಪ್ರಮುಖ ಶಕ್ತಿಗಳು",
            criticalGaps: "ಪ್ರಮುಖ ಕೊರತೆಗಳು",
            successRate: "ಅಂದಾಜು ಯಶಸ್ಸಿನ ದರ",
            tailoredResume: "ಕಸ್ಟಮೈಸ್ಡ್ ರೆಸ್ಯೂಮ್",
            copy: "ನಕಲಿಸಿ",
            downloadPdf: "ಪಿಡಿಎಫ್ ಡೌನ್ಲೋಡ್ ಮಾಡಿ",
            gapPlan: "ಕೌಶಲ್ಯದ ಅಂತರ ನಿವಾರಣಾ ಯೋಜನೆ",
            appTips: "ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಸಲಹೆಗಳು"
        },
`,
  bn: `        jobscout: {
            title: "এআই জব ডিসকভারি এজেন্ট",
            subtitle: "স্বয়ংক্রিয়ভাবে জব পোর্টাল স্ক্যান করে, বেতন, টেক স্ট্যাক এবং অভিজ্ঞতার ভিত্তিতে স্কোর করে এবং এটিএস-বান্ধব রেজ্যুমে তৈরি করে।",
            yourProfile: "আপনার প্রোফাইল",
            yourProfileDesc: "আপনার পোর্টফোলিও আমদানি করুন বা নিচে আপনার রেজ্যুমে পেস্ট করুন",
            importFromPortfolio: "পোর্টফোলিও থেকে আমদানি করুন",
            searchPrefs: "অনুসন্ধান পছন্দ",
            salaryRange: "বেতন সীমা",
            location: "অবস্থান",
            workMode: "কাজের ধরণ",
            experienceLevel: "অভিজ্ঞতার স্তর",
            scoutJobs: "আমার জন্য জব খুঁজুন",
            scanning: "জব পোর্টাল স্ক্যান করা হচ্ছে",
            scanningDesc: "LinkedIn, Naukri, Indeed, Glassdoor এ খোঁজা হচ্ছে...",
            jobsFound: "জব পাওয়া গেছে",
            all: "সব",
            worthApplying: "আবেদন করার যোগ্য",
            rescan: "আবার স্ক্যান করুন",
            generateResume: "রেজ্যুমে তৈরি করুন",
            backToJobs: "সব জবে ফিরে যান",
            topStrengths: "শীর্ষ শক্তি",
            criticalGaps: "গুরুতর অভাব",
            successRate: "আনুমানিক সফলতার হার",
            tailoredResume: "কাস্টমাইজড রেজ্যুমে",
            copy: "কপি করুন",
            downloadPdf: "পিডিএফ ডাউনলোড করুন",
            gapPlan: "স্কিল গ্যাপ রিকভারি প্ল্যান",
            appTips: "আবেদনের টিপস"
        },
`,
  gu: `        jobscout: {
            title: "એઆઈ જોબ ડિસ્કવરી એજન્ટ",
            subtitle: "આપોઆપ જોબ પોર્ટલ સ્કેન કરે છે, પગાર, ટેક સ્ટેક અને અનુભવના આધારે સ્કોર કરે છે, અને ATS-અનુકૂળ રેઝ્યૂમે બનાવે છે.",
            yourProfile: "તમારી પ્રોફાઇલ",
            yourProfileDesc: "તમારો પોર્ટફોલિયો આયાત કરો અથવા નીચે તમારો રેઝ્યુમે પેસ્ટ કરો",
            importFromPortfolio: "પોર્ટફોલિયોમાંથી આયાત કરો",
            searchPrefs: "શોધ પસંદગીઓ",
            salaryRange: "પગાર શ્રેણી",
            location: "સ્થાન",
            workMode: "કાર્ય મોડ",
            experienceLevel: "અનુભવ સ્તર",
            scoutJobs: "મારા માટે જોબ શોધો",
            scanning: "જોબ પોર્ટલ સ્કેન થઈ રહ્યું છે",
            scanningDesc: "LinkedIn, Naukri, Indeed, Glassdoor પર શોધી રહ્યા છીએ...",
            jobsFound: "નોકરીઓ મળી",
            all: "બધા",
            worthApplying: "અરજી કરવા યોગ્ય",
            rescan: "ફરીથી સ્કેન કરો",
            generateResume: "રેઝ્યુમે બનાવો",
            backToJobs: "બધી નોકરીઓ પર પાછા ફરો",
            topStrengths: "ટોચની શક્તિઓ",
            criticalGaps: "ગંભીર ખામીઓ",
            successRate: "અંદાજિત સફળતા દર",
            tailoredResume: "કસ્ટમાઇઝ્ડ રેઝ્યુમે",
            copy: "કૉપિ કરો",
            downloadPdf: "પીડીએફ ડાઉનલોડ કરો",
            gapPlan: "કૌશલ્ય અંતર પુનઃપ્રાપ્તિ યોજના",
            appTips: "અરજીઓ માટે ટિપ્સ"
        },
`,
  mr: `        jobscout: {
            title: "एआय जॉब डिस्कव्हरी एजंट",
            subtitle: "स्वयंचलितपणे जॉब पोर्टल स्कॅन करतो, पगार, टेक स्टॅक आणि अनुभवावर आधारित स्कोअर करतो, आणि ATS-फ्रेंडली रेझ्युमे बनवतो.",
            yourProfile: "तुमची प्रोफाइल",
            yourProfileDesc: "तुमचा पोर्टफोलिओ आयात करा किंवा खाली तुमचा रेझ्युमे पेस्ट करा",
            importFromPortfolio: "पोर्टफोलिओमधून आयात करा",
            searchPrefs: "शोध प्राधान्ये",
            salaryRange: "पगार श्रेणी",
            location: "स्थान",
            workMode: "कामाची पद्धत",
            experienceLevel: "अनुभव पातळी",
            scoutJobs: "माझ्यासाठी नोकऱ्या शोधा",
            scanning: "जॉब पोर्टल स्कॅन करत आहे",
            scanningDesc: "LinkedIn, Naukri, Indeed, Glassdoor वर शोधत आहे...",
            jobsFound: "नोकऱ्या सापडल्या",
            all: "सर्व",
            worthApplying: "अर्ज करण्यास योग्य",
            rescan: "पुन्हा स्कॅन करा",
            generateResume: "रेझ्युमे तयार करा",
            backToJobs: "सर्व नोकऱ्यांवर परत जा",
            topStrengths: "प्रमुख शक्ती",
            criticalGaps: "गंभीर त्रुटी",
            successRate: "अंदाजे यश दर",
            tailoredResume: "सानुकूलित रेझ्युमे",
            copy: "कॉपी करा",
            downloadPdf: "पीडीएफ डाउनलोड करा",
            gapPlan: "कौशल्य गॅप रिकव्हरी प्लॅन",
            appTips: "अर्ज करण्याच्या टिप्स"
        },
`
};

let parts = content.split('        common: {');
if (parts.length === 9) { // 8 languages + 1 initial split
  content = parts[0] + jobscoutTranslations.en + '        common: {' +
            parts[1] + jobscoutTranslations.hi + '        common: {' +
            parts[2] + jobscoutTranslations.te + '        common: {' +
            parts[3] + jobscoutTranslations.ta + '        common: {' +
            parts[4] + jobscoutTranslations.kn + '        common: {' +
            parts[5] + jobscoutTranslations.bn + '        common: {' +
            parts[6] + jobscoutTranslations.gu + '        common: {' +
            parts[7] + jobscoutTranslations.mr + '        common: {' +
            parts[8];
  
  fs.writeFileSync(file, content.replace('あなたのプロフィールDesc', 'yourProfileDesc'));
  console.log("Successfully injected jobscout.");
} else {
  console.log("Could not find exactly 8 'common: {' blocks to split around. Found:", parts.length - 1);
}
